//
// Created by os on 6/20/26.
//

#ifndef PROJECT_BASE_V1_1_THREADJOINALLTEST_HPP
#define PROJECT_BASE_V1_1_THREADJOINALLTEST_HPP
void ThreadJoinAllTest();
#endif //PROJECT_BASE_V1_1_THREADJOINALLTEST_HPP
